In [6]:
import pandas as pd
lookup = pd.read_csv('ranger equipment lookup.csv')
lookup

,item_id,point_name,equipment,parent_equipment_name,equipment_type
0,10000,Tubing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift
1,10001,Casing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift
2,10002,Tubing Pressure,BIG FIVE B 2H,BIG FIVE Well Pad,Gas Lift
3,10003,Casing Pressure,BIG FIVE B 2H,BIG FIVE Well Pad,Gas Lift
4,10004,Tubing Pressure,BLOODSTONE C 3H,BLOODSTONE C 3H D 4H Well Pad,Gas Lift
...,...,...,...,...,...
28454,71106,PLC Battery Voltage,PECAN Facility,NaN,Facility
28455,71107,PLC Battery Voltage,MATOCHA 1H Facility,NaN,Facility
28456,71108,PLC Battery Voltage,COLLEEN CALYPSO Facility,NaN,Facility
28457,71109,PLC Battery Voltage,HAWKEYE 9H 10H 11H Facility,NaN,Facility
28458,99999999,Tank Btm Level,10-23 Oil Tank 1,RANGER BEALL D-Pad Tank Battery,Storage

In [3]:
lookup[['equipment', 'item_id']].drop_duplicates()

                         equipment   item_id
0                    BIG FIVE A1 H     10000
1                    BIG FIVE A1 H     10001
2                    BIG FIVE B 2H     10002
3                    BIG FIVE B 2H     10003
4                  BLOODSTONE C 3H     10004
...                            ...       ...
28454               PECAN Facility     71106
28455          MATOCHA 1H Facility     71107
28456     COLLEEN CALYPSO Facility     71108
28457  HAWKEYE 9H 10H 11H Facility     71109
28458             10-23 Oil Tank 1  99999999

[28459 rows x 2 columns]

In [4]:
lookup.groupby(['equipment', 'item_id']).apply(len).unique()

array([1], dtype=int64)

In [10]:
import pandas as pd
iron_iQ = pd.read_excel('Iron IQ Well Name to Accounting ID Table.xlsx', engine='openpyxl')
iron_iQ

                 Name  Accounting Number
0    ADDAX HUNTER #1H          203216.01
1    ADDAX HUNTER #2H          203217.01
2    ADDAX HUNTER #7H          204359.01
3    ADDAX HUNTER #8H          204360.01
4     ADDAX HUNTER 3H          203218.01
..                ...                ...
620  ZEBRA HUNTER #4H          207662.01
621  ZEBRA HUNTER #6H          204348.01
622  ZEBRA HUNTER #7H          204349.01
623        ZIRCON A1H          204755.01
624        ZIRCON B2H          204756.01

[625 rows x 2 columns]

##### Outer join with the equipment of look_up file and Iron_Iq file

In [68]:
# outer_join_01 = pd.merge(lookup, iron_iQ, left_on='equipment', right_on='Name', how='outer')
# outer_join_01

outer_join_01 = pd.merge(lookup, iron_iQ, left_on='equipment', right_on='Name', how='left')
outer_join_01

,item_id,point_name,equipment,parent_equipment_name,equipment_type,well_name,Name,Accounting Number
0,10000,Tubing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H,BIG FIVE A1 H,204600.01
1,10001,Casing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H,BIG FIVE A1 H,204600.01
2,10002,Tubing Pressure,BIG FIVE B 2H,BIG FIVE Well Pad,Gas Lift,BIG FIVE B 2H,BIG FIVE B 2H,204601.01
3,10003,Casing Pressure,BIG FIVE B 2H,BIG FIVE Well Pad,Gas Lift,BIG FIVE B 2H,BIG FIVE B 2H,204601.01
4,10004,Tubing Pressure,BLOODSTONE C 3H,BLOODSTONE C 3H D 4H Well Pad,Gas Lift,BLOODSTONE C 3H,BLOODSTONE C 3H,204686.01
...,...,...,...,...,...,...,...,...
28454,71106,PLC Battery Voltage,PECAN Facility,NaN,Facility,PECAN,NaN,NaN
28455,71107,PLC Battery Voltage,MATOCHA 1H Facility,NaN,Facility,MATOCHA 1H,NaN,NaN
28456,71108,PLC Battery Voltage,COLLEEN CALYPSO Facility,NaN,Facility,COLLEEN CALYPSO,NaN,NaN
28457,71109,PLC Battery Voltage,HAWKEYE 9H 10H 11H Facility,NaN,Facility,HAWKEYE 9H 10H 11H,NaN,NaN
28458,99999999,Tank Btm Level,10-23 Oil Tank 1,RANGER BEALL D-Pad Tank Battery,Storage,10-23,NaN,NaN

In [69]:
nan_rows = outer_join_01[outer_join_01.isna().any(axis=1)]
nan_rows

,item_id,point_name,equipment,parent_equipment_name,equipment_type,well_name,Name,Accounting Number
100,10114,Flow Rate,BIG FIVE A1 H Water Meter,BIG FIVE A1 H,Water Meter,BIG FIVE A1 H,NaN,NaN
101,10115,Flow Today,BIG FIVE A1 H Water Meter,BIG FIVE A1 H,Water Meter,BIG FIVE A1 H,NaN,NaN
102,10116,Flow Yesterday,BIG FIVE A1 H Water Meter,BIG FIVE A1 H,Water Meter,BIG FIVE A1 H,NaN,NaN
103,10117,Flow Rate,BIG FIVE A1 H Oil Meter,BIG FIVE A1 H,Oil Meter,BIG FIVE A1 H,NaN,NaN
104,10118,Flow Today,BIG FIVE A1 H Oil Meter,BIG FIVE A1 H,Oil Meter,BIG FIVE A1 H,NaN,NaN
...,...,...,...,...,...,...,...,...
28454,71106,PLC Battery Voltage,PECAN Facility,NaN,Facility,PECAN,NaN,NaN
28455,71107,PLC Battery Voltage,MATOCHA 1H Facility,NaN,Facility,MATOCHA 1H,NaN,NaN
28456,71108,PLC Battery Voltage,COLLEEN CALYPSO Facility,NaN,Facility,COLLEEN CALYPSO,NaN,NaN
28457,71109,PLC Battery Voltage,HAWKEYE 9H 10H 11H Facility,NaN,Facility,HAWKEYE 9H 10H 11H,NaN,NaN
28458,99999999,Tank Btm Level,10-23 Oil Tank 1,RANGER BEALL D-Pad Tank Battery,Storage,10-23,NaN,NaN

In [70]:
name_nan_rows = outer_join_01[outer_join_01['Accounting Number'].isna()]
name_nan_rows

,item_id,point_name,equipment,parent_equipment_name,equipment_type,well_name,Name,Accounting Number
100,10114,Flow Rate,BIG FIVE A1 H Water Meter,BIG FIVE A1 H,Water Meter,BIG FIVE A1 H,NaN,NaN
101,10115,Flow Today,BIG FIVE A1 H Water Meter,BIG FIVE A1 H,Water Meter,BIG FIVE A1 H,NaN,NaN
102,10116,Flow Yesterday,BIG FIVE A1 H Water Meter,BIG FIVE A1 H,Water Meter,BIG FIVE A1 H,NaN,NaN
103,10117,Flow Rate,BIG FIVE A1 H Oil Meter,BIG FIVE A1 H,Oil Meter,BIG FIVE A1 H,NaN,NaN
104,10118,Flow Today,BIG FIVE A1 H Oil Meter,BIG FIVE A1 H,Oil Meter,BIG FIVE A1 H,NaN,NaN
...,...,...,...,...,...,...,...,...
28454,71106,PLC Battery Voltage,PECAN Facility,NaN,Facility,PECAN,NaN,NaN
28455,71107,PLC Battery Voltage,MATOCHA 1H Facility,NaN,Facility,MATOCHA 1H,NaN,NaN
28456,71108,PLC Battery Voltage,COLLEEN CALYPSO Facility,NaN,Facility,COLLEEN CALYPSO,NaN,NaN
28457,71109,PLC Battery Voltage,HAWKEYE 9H 10H 11H Facility,NaN,Facility,HAWKEYE 9H 10H 11H,NaN,NaN
28458,99999999,Tank Btm Level,10-23 Oil Tank 1,RANGER BEALL D-Pad Tank Battery,Storage,10-23,NaN,NaN

In [74]:
a = list(name_nan_rows['well_name'].unique())
a

['BIG FIVE A1 H',
 'BIG FIVE B 2H',
 'BLOODSTONE C 3H',
 'BLOODSTONE D H',
 'BLOODSTONE D 4H',
 'CARBONITE A1H',
 'CARBONITE B2H',
 'CARBONITE C3H',
 'CORAL A 1H',
 'CORAL B 2H',
 'CORAL C 3H',
 'DIAMOND A1H',
 'LAGER UNIT 4H',
 'DRAGONSTONE A 1H',
 'DRAGONSTONE B 2H',
 'EMERALD A1H',
 'EMERALD B2H',
 'CINCO RANCH E #5H',
 'HALITE A1H',
 'HALITE B2H',
 'PLATYPUS HUNTER #2H',
 'PLATYPUS HUNTER #3H',
 'PYRITE 1H',
 'HAWN HOLT 21H',
 'Pyrtie 1H',
 'LABRADORITE A 1H',
 'LABRADORITE B 2H',
 'LABRADORITE C 3H',
 'MAMMOTH A 1H',
 'MAMMOTH B 2H',
 'LOMBARDO #1H',
 'LOMBARDO 2H',
 'KYBER A 1H',
 'KYBER B 2H',
 'KYBER C 3H',
 'KYBER D 4H',
 'MOONSTONE A1H',
 'MOONSTONE B2H',
 'EFFENBERGER #4H',
 'EFFENBERGER #5H',
 'RATTLER A 1H',
 'RATTLER B 2H',
 'ROCK CREEK #11H',
 'ROCK CREEK RANCH UNIT 12H',
 'ROCK CREEK RANCH 25H',
 'QUARTZ 1H',
 'SAPPHIRE A1H',
 'SAPPHIRE B 2H',
 'PILSNER HUNTER #6H',
 'PILSNER HUNTER #7H',
 'SERPENTINE A 1H',
 'SERPENTINE B 2H',
 'SERPENTINE C 3H',
 'SHARKTOOTH (SA) UNIT 1 1H',
 'SHARKTOOTH (SA) UNIT 2 2H',
 'TOPAZ A 1H',
 'TOPAZ B 2H',
 'TOPAZ C 3H',
 'TURQUOISE A 1H',
 'TURQUOISE B 2H',
 'TURQUOISE C 3H',
 'BIG FIVE',
 'CARBONITE',
 'EMERALD',
 'HALITE',
 'HAWN HOLT/PYRITE',
 'LABRADORITE',
 'MAMMOTH Unknown',
 'MAMMOTH Unknown Tank 3',
 'MAMMOTH Unknown Tank 4',
 'MAMMOTH Unknown Tank 5',
 'MAMMOTH Unknown Tank 6',
 'MAMMOTH Unknown Tank 7',
 'MAMMOTH Unknown Tank 8',
 'MOONSTONE',
 'RATTLER',
 'DIAMOND LAGER',
 'SAPPHIRE',
 'SAPPHIRE  6',
 'SHARKTOOTH',
 'BRUCITE/KOSMO/PORTER',
 'SHARKTOOTH Water Tank',
 'BRUCITE/KOSMO/PORTER Water Tank',
 'QUARTZ',
 'BLOODSTONE',
 'CORAL',
 'DIAMOND',
 'DRAGONSTONE Remove Device',
 'HAWN HOLT',
 'MAMMOTH',
 'ROCK CREEK RANCH QUARTZ',
 'SERPENTINE',
 'TOPAZ',
 'TURQUOISE',
 'KYBER',
 'MAMMOTH Well 1 LACT',
 'MAMMOTH Well 2 LACT',
 'MAMMOTH LACT',
 nan,
 'WOMBAT UNIT 5H',
 'WOMBAT STAG A6H',
 'WOMBAT STAG B7H',
 'WAVELLITE A1H',
 'WAVELLITE B2H',
 'WAVELLITE C3H',
 'WAVELLITE/WOMBAT',
 'HAWN HOLT #28H',
 'HAWN HOLT #22H',
 'HAWN HOLT #12H',
 'TREMOLITE A1H',
 'TREMOLITE B2H',
 'HAWN HOLT #13H',
 'HAWN HOLT/TREMOLITE LACT',
 'HAWN HOLT/TREMOLITE',
 'ZIRCON A1H',
 'ZIRCON B2H',
 'CAROL-ROBIN (SA) UNIT 1 1H',
 'CAROL-ROBIN (SA) UNIT 2 2H',
 'B.S C3D4/ZIRCON',
 'B.S C3D4/ZIRCON Water Tank',
 'CAROL ROBINS',
 'CAROL ROBINS Water Tank',
 'B.S C3D4/ZIRCON LACT 3',
 'CAROL ROBINS LACT 1',
 'CAROL ROBINS LACT 3',
 'ZIRCON/CAROL  LACT',
 'ZIRCON/CAROL',
 'AQUAMARINE E5H',
 'AQUAMARINE F6H',
 'BOWIE #1H',
 'R.WASHINGTON #1H',
 'BOWIE #1H-WASHINGTON CT LPR',
 'BOWIE #1H-WASHINGTON CT',
 'AQUAMARINE/BOWIE/WASHINGTON',
 'BRUCITE A1H',
 'BRUCITE B2H',
 'KOSMO #1H',
 'KOSMO #2H',
 'KOSMO #3H',
 'PORTER #1H',
 'CINNABAR',
 'NEVELS ADDAX NAB HUNTER Addax',
 'NEVELS ADDAX 1H',
 'NAB HUNTER 1H',
 'ADDAX HUNTER #1H',
 'ADDAX HUNTER #2H',
 'ADDAX HUNTER 3H',
 'CINNABAR A 1H',
 'CINNABAR B 2H',
 'MOONSTONE VRU',
 'WHITE OAK B2H Water Tank',
 'WHITE OAK B2H',
 'WHITE OAK A1H Water Tank',
 'WHITE OAK A1H',
 'WHITE OAK Cooler Scrubber',
 'WHITE OAK B2H LP',
 'WHITE OAK B2H HP',
 'WHITE OAK',
 'WHITE OAK A1H HP',
 'WHITE OAK A1H LP',
 'WHITE OAK  Scrubber',
 'WHITE OAK LP',
 'WHITE OAK HP',
 'WHITE OAK A1H Inj',
 'WHITE OAK B2H Inj',
 'EBONY/IVORY',
 'SOUTHERN HUNTER/AMBER',
 'SOUTHERN HUNTER AMBER #1H',
 'SOUTHERN HUNTER AMBER #2H',
 'EBONY 1H',
 'IVORY 1H',
 'SHINER RANCH LPR',
 'SHINER RANCH CT',
 'SOUTHERN HUNTER/AMBER/EBONY/IVORY',
 'DAWLEAN RICHARDSON',
 'DAWLEAN RICHARDSON Fuel',
 'DAWLEAN RICHARDSON UNIT 1H',
 'DAWLEAN RICHARDSON UNIT 2H',
 'HAWN HOLT/RUTILE  6',
 'HAWN HOLT/RUTILE',
 'HAWN D.A. A 1H',
 'HAWN D.A. B 2H',
 'RUTILE A1H',
 'RUTILE B2H',
 'HAWN HOLT A1H B2H',
 'RUTILE',
 'WALNUT A1H Water Tank',
 'WALNUT A1H',
 'WALNUT B2H Water Tank',
 'WALNUT B2H',
 'WALNUT Cooler Scrubber',
 'WALNUT B2H LP',
 'WALNUT B2H HP',
 'WALNUT',
 'WALNUT A1H HP',
 'WALNUT A1H LP',
 'WALNUT  Scrubber',
 'WALNUT HP',
 'WALNUT LP',
 'TestLab CLX',
 'CANNONADE SPRINGS/AZURITE',
 'CANNONADE SPRINGS UNIT 1H',
 'CANNONADE SPRINGS UNIT 2H',
 'AZURITE A1H',
 'AZURITE B2H',
 'CANNONADE SPRINGS',
 'AZURITE',
 'CHARON/GATOR',
 'CHARON A1H',
 'CHARON B2H',
 'GATOR #2H',
 'GATOR #3H',
 'GATOR',
 'CHARON',
 'TREMOLITE',
 'HORNED G LP',
 'HORNED H LP',
 'CHARON/GATOR  Tank',
 'OPAL/MUNSON RANCH Water Tank #1',
 'OPAL/MUNSON RANCH Water Tank #2',
 'OPAL/MUNSON RANCH  #1',
 'OPAL/MUNSON RANCH  #2',
 'OPAL/MUNSON RANCH  #3',
 'OPAL/MUNSON RANCH  #4',
 'OPAL 1H',
 'MUNSON RANCH 24H',
 'OPAL/MUNSON RANCH',
 'GEORG EF/Maple Water Tank #1',
 'GEORG EF/Maple Water Tank #2',
 'GEORG EF/Maple  #1',
 'GEORG EF/Maple  #2',
 'GEORG EF/Maple  #3',
 'GEORG EF/Maple  #4',
 'MAPLE A1H',
 'MAPLE B2H',
 'GEORG EF 1H',
 'GEORG EF 2H',
 'Pump',
 'MAPLE C3H',
 'MAPLE D4H',
 'ADDAX HUNTER 6H  - LAVACA',
 'ADDAX HUNTER #7H  - LAVACA',
 'ADDAX HUNTER #8H  - LAVACA',
 'ADDAX HUNTER #1H   - LAVACA',
 'ADDAX HUNTER #1H  - LAVACA',
 'ADDAX HUNTER #2H   - LAVACA',
 'ADDAX HUNTER #2H  - LAVACA',
 'ADDAX HUNTER 3H   - LAVACA',
 'ADDAX HUNTER 3H  - LAVACA',
 'ADDAX HUNTER 6H   - LAVACA',
 'ADDAX HUNTER #7H   - LAVACA',
 'ADDAX HUNTER #8H   - LAVACA',
 'AMBER #1H   - LAVACA',
 'AMBER #1H  - LAVACA',
 'AMBER #2H   - LAVACA',
 'AMBER #2H  - LAVACA',
 'AMBER-LAGER A (SA) 1H  - LAVACA',
 'AMBER-LAGER A (SA) 1H   - LAVACA',
 'AMBER-LAGER B (SA) 2H  - LAVACA',
 'AMBER-LAGER B (SA) 2H   - LAVACA',
 'Lavaca Amber Porter 2H 3H CT LPR',
 'Lavaca Amber Porter CT',
 'AMETHYST 1H   - LAVACA',
 'AMETHYST 1H  - LAVACA',
 'ANTEATER #1H   - LAVACA',
 'ANTEATER #1H  - LAVACA',
 'Lavaca Aquamarine CT',
 'Lavaca Aquamarine CT LPR',
 'ARLEDGE RANCH #1H   - LAVACA',
 'ARLEDGE RANCH #1H  - LAVACA',
 'ARMADILLO A (SA) 1H   - LAVACA',
 'ARMADILLO A (SA) 1H  - LAVACA',
 'ARMADILLO B (SA) 2H   - LAVACA',
 'ARMADILLO B (SA) 2H  - LAVACA',
 'ARMADILLO C (SA) 3H   - LAVACA',
 'ARMADILLO C (SA) 3H  - LAVACA',
 'AXIS #1H   - LAVACA',
 'AXIS #1H  - LAVACA',
 'AXIS #2H   - LAVACA',
 'AXIS #2H  - LAVACA',
 'AXIS #3H   - LAVACA',
 'AXIS #3H  - LAVACA',
 'AZURITE A1H   - LAVACA',
 'AZURITE B2H   - LAVACA',
 'BADGER #1H   - LAVACA',
 'BADGER #1H  - LAVACA',
 'BERTHA #1H   - LAVACA',
 'BERTHA #1H  - LAVACA',
 'BIG FIVE A1 H   - LAVACA',
 'BIG FIVE A1 H  - LAVACA',
 'BIG FIVE B 2H   - LAVACA',
 'BIG FIVE B 2H  - LAVACA',
 'BLONDE #2   - LAVACA',
 'BLONDE #2  - LAVACA',
 'BLONDE #3H   - LAVACA',
 'BLONDE #3H  - LAVACA',
 'BLONDE #4H   - LAVACA',
 'BLONDE #4H  - LAVACA',
 'BLONDE #5H   - LAVACA',
 'BLONDE #5H  - LAVACA',
 'BLONDE #6H   - LAVACA',
 'BLONDE #6H  - LAVACA',
 'BLONDE #7H   - LAVACA',
 'BLONDE #7H  - LAVACA',
 'BLONDE #8H   - LAVACA',
 'BLONDE #8H  - LAVACA',
 'BLONDE #9H   - LAVACA',
 'BLONDE #9H  - LAVACA',
 'BLOODSTONE C 3H   - LAVACA',
 'BLOODSTONE C 3H  - LAVACA',
 'BLOODSTONE D 4H   - LAVACA',
 'BLOODSTONE D 4H  - LAVACA',
 'BOCK #4H   - LAVACA',
 'BOCK #4H  - LAVACA',
 'BOCK #5H   - LAVACA',
 'BOCK #5H  - LAVACA',
 'BONGO HUNTER #3H   - LAVACA',
 'BONGO HUNTER #3H  - LAVACA',
 'BONGO HUNTER #4H   - LAVACA',
 'BONGO HUNTER #4H  - LAVACA',
 'BONGO HUNTER #5H   - LAVACA',
 'BONGO HUNTER #5H  - LAVACA',
 'Lavaca Bongo Hunter CT',
 'Lavaca Bongo Hunter CT LPR',
 'BONGO SOUTH #2H   - LAVACA',
 'BONGO SOUTH #2H  - LAVACA',
 'Lavaca Bongo Stag CT',
 'Lavaca Bongo Stag CT LPR',
 'Lavaca Bowie Washington CT',
 'Lavaca Bowie Washington CT LPR',
 'BRUCITE A1H   - LAVACA',
 'BRUCITE A1H  - LAVACA',
 'BRUCITE B2H   - LAVACA',
 'BRUCITE B2H  - LAVACA',
 'BUFFALO HUNTER #2H   - LAVACA',
 'BUFFALO HUNTER #2H  - LAVACA',
 'BUFFALO HUNTER #3H   - LAVACA',
 'BUFFALO HUNTER #3H  - LAVACA',
 'BUFFALO HUNTER #4H   - LAVACA',
 'BUFFALO HUNTER #4H  - LAVACA',
 'Lavaca Cannonade Springs CT',
 'Lavaca Cannonade Springs CT LPR',
 'CARACARA UNIT 1H   - LAVACA',
 'CARACARA UNIT 1H  - LAVACA',
 'CARACARA UNIT 2H   - LAVACA',
 'CARACARA UNIT 2H  - LAVACA',
 'CARACARA UNIT 4H   - LAVACA',
 'CARACARA UNIT 4H  - LAVACA',
 'CARBONITE A1H   - LAVACA',
 'CARBONITE A1H  - LAVACA',
 'CARBONITE B2H   - LAVACA',
 'CARBONITE B2H  - LAVACA',
 'CARBONITE C3H   - LAVACA',
 'CARBONITE C3H  - LAVACA',
 'CAROL-ROBIN (SA) UNIT 1 1H   - LAVACA',
 'CAROL-ROBIN (SA) UNIT 1 1H  - LAVACA',
 'CAROL-ROBIN (SA) UNIT 2 2H   - LAVACA',
 'CAROL-ROBIN (SA) UNIT 2 2H  - LAVACA',
 'CHARON A1H   - LAVACA',
 'CHARON B2H   - LAVACA',
 'CHICKEN HAWK #1H   - LAVACA',
 'CHICKEN HAWK #1H  - LAVACA',
 'Lavaca Chickenhawk CT',
 'CINCO RANCH E #5H   - LAVACA',
 'CINCO RANCH E #5H  - LAVACA',
 'CINCO J RANCH LTD #1H    - LAVACA',
 'CINCO J RANCH LTD #1H   - LAVACA',
 'CINCO J RANCH LTD UNIT 2H   - LAVACA',
 'CINCO J RANCH LTD UNIT 2H  - LAVACA',
 'Lavaca Cinco J Ranch CT',
 'Lavaca Cinco J Ranch CT LPR',
 'CINNABAR A 1H   - LAVACA',
 'CINNABAR A 1H  - LAVACA',
 'CINNABAR B 2H   - LAVACA',
 'CINNABAR B 2H  - LAVACA',
 'COYOTE A (SA) 1H   - LAVACA',
 'COYOTE A (SA) 1H  - LAVACA',
 'COYOTE B (SA) 2H   - LAVACA',
 'COYOTE B (SA) 2H  - LAVACA',
 'CROC #1H   - LAVACA',
 'CROC #1H  - LAVACA',
 'CROC #2H   - LAVACA',
 'CROC #2H  - LAVACA',
 'DEEDRA-LORI (SA) UNIT 3 3H   - LAVACA',
 'DEEDRA-LORI (SA) UNIT 3 3H  - LAVACA',
 'DEEDRA-LORI (SA) UNIT 4 4H   - LAVACA',
 'DEEDRA-LORI (SA) UNIT 4 4H  - LAVACA',
 'DIAMOND A1H   - LAVACA',
 'DIAMOND A1H  - LAVACA',
 'DINGO HUNTER #1H   - LAVACA',
 'DINGO HUNTER #1H  - LAVACA',
 'DINGO HUNTER #2H   - LAVACA',
 'DINGO HUNTER #2H  - LAVACA',
 'DINGO HUNTER #3H   - LAVACA',
 'DINGO HUNTER #3H  - LAVACA',
 'Lavaca Dingo Platypus CT',
 'Lavaca Dingo Platypus CT LPR',
 'DICKSON ALLEN #1H (Devon)   - LAVACA',
 'DICKSON ALLEN #1H (Devon)  - LAVACA',
 'Lavaca Douglas Raab CT',
 'Lavaca Douglas Raab CT LP',
 'DRAGONSTONE A 1H   - LAVACA',
 'DRAGONSTONE A 1H  - LAVACA',
 'DRAGONSTONE B 2H   - LAVACA',
 'DRAGONSTONE B 2H  - LAVACA',
 'EBONY 1H   - LAVACA',
 'EBONY 1H  - LAVACA',
 'EFFENBERGER #4H   - LAVACA',
 'EFFENBERGER #4H  - LAVACA',
 'EFFENBERGER #5H   - LAVACA',
 'EFFENBERGER #5H  - LAVACA',
 'EFFENBERGER-SCHACHERL #4H   - LAVACA',
 'EFFENBERGER-SCHACHERL #4H  - LAVACA',
 'ELK HUNTER #4H   - LAVACA',
 'ELK HUNTER #4H  - LAVACA',
 'ELK HUNTER #5H   - LAVACA',
 'ELK HUNTER #5H  - LAVACA',
 'ELK HUNTER #6H   - LAVACA',
 'ELK HUNTER #6H  - LAVACA',
 'EMERALD A1H   - LAVACA',
 'EMERALD A1H  - LAVACA',
 'EMERALD B2H   - LAVACA',
 'EMERALD B2H  - LAVACA',
 'RCR FLETCHER #1   - LAVACA',
 'RCR FLETCHER #1  - LAVACA',
 'RCR FLETCHER #2   - LAVACA',
 'RCR FLETCHER #2  - LAVACA',
 'RCR FLETCHER #3   - LAVACA',
 'RCR FLETCHER #3  - LAVACA',
 'FURRH 4H   - LAVACA',
 'FURRH 4H  - LAVACA',
 'FURRH 5H   - LAVACA',
 'FURRH 5H  - LAVACA',
 'GARNET 1H   - LAVACA',
 'GARNET 1H  - LAVACA',
 'GATOR #2H   - LAVACA',
 'GATOR #2H  - LAVACA',
 'GATOR #3H   - LAVACA',
 'GATOR #3H  - LAVACA',
 'GEO HUNTER #1H   - LAVACA',
 'GEO HUNTER #1H  - LAVACA',
 'GEO HUNTER #2H   - LAVACA',
 'GEO HUNTER #2H  - LAVACA',
 'GEO HUNTER #3H   - LAVACA',
 'GEO HUNTER #3H  - LAVACA',
 'GOLDEN BEAR (SA) 1H   - LAVACA',
 'GOLDEN BEAR (SA) 1H  - LAVACA',
 'GONZO HUNTER #2H   - LAVACA',
 'GONZO HUNTER #3H   - LAVACA',
 'GONZO HUNTER #3H  - LAVACA',
 'GONZO HUNTER #4H   - LAVACA',
 'GONZO HUNTER #4H  - LAVACA',
 'GONZO NORTH #7H   - LAVACA',
 'GONZO NORTH #7H  - LAVACA',
 'GONZO NORTH #8H   - LAVACA',
 'GONZO NORTH #8H  - LAVACA',
 'GONZO NORTH #9H   - LAVACA',
 'GONZO NORTH #9H  - LAVACA',
 'Lavaca Gonzos Buffalo H CT GL',
 'Lavaca Gonzos Buffalo H CT LPR',
 'HALITE A1H   - LAVACA',
 'Lavaca Halite/Ceres CT GL',
 'HALITE B2H   - LAVACA',
 'HAWG HUNTER #1H   - LAVACA',
 'HAWG HUNTER #1H  - LAVACA',
 'HAWG HUNTER #3H   - LAVACA',
 'HAWG HUNTER #3H  - LAVACA',
 'HAWG HUNTER #4H   - LAVACA',
 'HAWG HUNTER #4H  - LAVACA',
 'HAWG HUNTER #5H   - LAVACA',
 'HAWG HUNTER #5H  - LAVACA',
 'Lavaca Hawnda CT',
 'Lavaca Hawnda CT LPR',
 'HAWN HOLT #13H   - LAVACA',
 'HAWN HOLT #13H  - LAVACA',
 'HAWN HOLT #16   - LAVACA',
 'HAWN HOLT #16  - LAVACA',
 'HAWN HOLT #17   - LAVACA',
 'HAWN HOLT #17  - LAVACA',
 'Lavaca Hawn Holt 1819 CT',
 'HAWN HOLT 21H   - LAVACA',
 'HAWN HOLT 21H  - LAVACA',
 'HAWN HOLT #2H   - LAVACA',
 'HAWN HOLT #2H  - LAVACA',
 'HAWN HOLT #6H   - LAVACA',
 'HAWN HOLT #6H  - LAVACA',
 'Lavaca Hawn Holt CT',
 'Lavaca Hawn Holt CT LPR',
 'Lavaca Heatwave Leal CT',
 'Lavaca Heatwave Leal CT LPR',
 'HEDGEHOG #1H   - LAVACA',
 'HEDGEHOG #1H  - LAVACA',
 'Lavaca Hinze CT',
 'Lavaca Hinze CT LPR',
 'HIPPO HUNTER 3H   - LAVACA',
 'HIPPO HUNTER 3H  - LAVACA',
 'HIPPO HUNTER #5H   - LAVACA',
 'HIPPO HUNTER #5H  - LAVACA',
 'HIPPO HUNTER #6H   - LAVACA',
 'HIPPO HUNTER #6H  - LAVACA',
 'IVORY 1H   - LAVACA',
 'IVORY 1H  - LAVACA',
 'Lavaca Jackalope CT',
 'Lavaca Jackelope 1H 2H LP CT',
 'JAKE BERGER CATTLE #1H   - LAVACA',
 'JAKE BERGER CATTLE #1H  - LAVACA',
 'JAKE BERGER CATTLE CO 2H   - LAVACA',
 'JAKE BERGER CATTLE CO 2H  - LAVACA',
 'JAKE BERGER CATTLE CO 4H   - LAVACA',
 'JAKE BERGER CATTLE CO 4H  - LAVACA',
 'JAKE BERGER CATTLE CO 5H   - LAVACA',
 'JAKE BERGER CATTLE CO 5H  - LAVACA',
 'Lavaca Jake Berger Jr CT',
 'RCR JANE #1   - LAVACA',
 'RCR JANE #1  - LAVACA',
 'RCR JANE #2   - LAVACA',
 'RCR JANE #2  - LAVACA',
 'RCR JANE #4   - LAVACA',
 'RCR JANE #4  - LAVACA',
 'RCRS JANE #6H   - LAVACA',
 'RCRS JANE #6H  - LAVACA',
 'RCRS JANE #7H   - LAVACA',
 'RCRS JANE #7H  - LAVACA',
 'JEFFERY UNIT #4H   - LAVACA',
 'JEFFERY UNIT #4H  - LAVACA',
 'JEFFERY UNIT #5H   - LAVACA',
 'JEFFERY UNIT #5H  - LAVACA',
 'JOSEPH SIMPER #1H   - LAVACA',
 'JOSEPH SIMPER #1H  - LAVACA',
 'KOSMO #1H   - LAVACA',
 'KOSMO #1H  - LAVACA',
 'KOSMO #2H   - LAVACA',
 'KOSMO #2H  - LAVACA',
 'KOSMO #3H   - LAVACA',
 'KOSMO #3H  - LAVACA',
 'KUDU HUNTER #3H   - LAVACA',
 'KUDU HUNTER #3H  - LAVACA',
 'KUDU HUNTER #4H   - LAVACA',
 'KUDU HUNTER #4H  - LAVACA',
 'KUDU HUNTER #5H   - LAVACA',
 'KUDU HUNTER #5H  - LAVACA',
 'KUDU HUNTER #6H   - LAVACA',
 'KUDU HUNTER #6H  - LAVACA',
 'KUDU HUNTER #7H   - LAVACA',
 'KUDU HUNTER #7H  - LAVACA',
 'KUDU HUNTER #8H   - LAVACA',
 'KUDU HUNTER #8H  - LAVACA',
 'KUDU HUNTER #9H   - LAVACA',
 'KUDU HUNTER #9H  - LAVACA',
 'KUSAK #2H   - LAVACA',
 'KUSAK #2H  - LAVACA',
 'KUSAK #3H   - LAVACA',
 'KUSAK #3H  - LAVACA',
 'LABRADORITE A 1H   - LAVACA',
 'LABRADORITE A 1H  - LAVACA',
 'LABRADORITE B 2H   - LAVACA',
 'LABRADORITE B 2H  - LAVACA',
 'LABRADORITE C 3H   - LAVACA',
 'LABRADORITE C 3H  - LAVACA',
 'LAGER #1H   - LAVACA',
 'LAGER #1H  - LAVACA',
 'LAGER #2H   - LAVACA',
 'LAGER #2H  - LAVACA',
 'LAGER #3H   - LAVACA',
 'LAGER #3H  - LAVACA',
 'LAGER UNIT 4H   - LAVACA',
 'LAGER UNIT 4H  - LAVACA',
 'LEOPARD HUNTER #1H   - LAVACA',
 'LEOPARD HUNTER #1H  - LAVACA',
 'LEOPARD HUNTER #4H   - LAVACA',
 'LEOPARD HUNTER #4H  - LAVACA',
 'LEOPARD HUNTER #5H   - LAVACA',
 'LEOPARD HUNTER #5H  - LAVACA',
 'LEOPARD HUNTER #6H   - LAVACA',
 'LEOPARD HUNTER #6H  - LAVACA',
 'LEOPARD HUNTER #7H   - LAVACA',
 'LEOPARD HUNTER #7H  - LAVACA',
 'L & LEE UNIT 7H   - LAVACA',
 'L & LEE UNIT 7H  - LAVACA',
 'Lavaca LJ Lee CT',
 'Lavaca LJ Lee RCR Manning 1H',
 'Lavaca LJ Lee RCR Manning 2H',
 'LOTT 5H   - LAVACA',
 'LOTT 5H  - LAVACA',
 'LOTT 6H   - LAVACA',
 'LOTT 6H  - LAVACA',
 'LOTT 7H   - LAVACA',
 'LOTT 7H  - LAVACA',
 'Lavaca Mammoth Lm CT',
 'Lavaca Mammoth Lm CT LPR',
 'MARCIA-SHELLY (SA) UNIT 1 1H   - LAVACA',
 'MARCIA-SHELLY (SA) UNIT 1 1H  - LAVACA',
 'MARCIA-SHELLY (SA) UNIT 2 2H   - LAVACA',
 'MARCIA-SHELLY (SA) UNIT 2 2H  - LAVACA',
 'MATIAS #4H   - LAVACA',
 'MATIAS #4H  - LAVACA',
 'MATIAS #5H   - LAVACA',
 'MATIAS #5H  - LAVACA',
 'Lavaca Mccreary Javelina CT',
 'Lavaca Mccreary Javelina CT LPR',
 'Lavaca Mccreary Technik CT Hp',
 'Lavaca Mccreay Technik CT LPR',
 'MOONSTONE A1H   - LAVACA',
 'MOONSTONE A1H  - LAVACA',
 'MOONSTONE B2H   - LAVACA',
 'MOONSTONE B2H  - LAVACA',
 'MOOSE HUNTER #1H   - LAVACA',
 'MOOSE HUNTER #1H  - LAVACA',
 'MOOSE HUNTER #5H   - LAVACA',
 'MOOSE HUNTER #5H  - LAVACA',
 'MOOSE HUNTER #6H   - LAVACA',
 'MOOSE HUNTER #6H  - LAVACA',
 'MUNSON RANCH 13H   - LAVACA',
 'MUNSON RANCH 13H  - LAVACA',
 'MUNSON RANCH 14H   - LAVACA',
 'MUNSON RANCH 14H  - LAVACA',
 'MUNSON RANCH 15H   - LAVACA',
 'MUNSON RANCH 15H  - LAVACA',
 'MUNSON RANCH #19H   - LAVACA',
 'MUNSON RANCH #19H  - LAVACA',
 'MUNSON RANCH 24H   - LAVACA',
 'MUNSON RANCH 24H  - LAVACA',
 'NAB HUNTER 1H   - LAVACA',
 'NAB HUNTER 1H  - LAVACA',
 'NEVELS ADDAX 1H   - LAVACA',
 'NEVELS ADDAX 1H  - LAVACA',
 'Nitro B 3H   - LAVACA',
 'Nitro B 3H  - LAVACA',
 'Nitro B 4H   - LAVACA',
 'Nitro B 4H  - LAVACA',
 'O BORCHERS E #1H   - LAVACA',
 'O BORCHERS E #1H  - LAVACA',
 'OPAL 1H   - LAVACA',
 'OPAL 1H  - LAVACA',
 'ORYX HUNTER #2H   - LAVACA',
 'ORYX HUNTER #2H  - LAVACA',
 'Lavaca Oryx Furr H CT',
 'Lavaca Oryx Furr H CT LPR',
 'ORYX HUNTER #3H   - LAVACA',
 'ORYX HUNTER #3H  - LAVACA',
 'ORYX HUNTER #4H   - LAVACA',
 'ORYX HUNTER #4H  - LAVACA',
 'PILSNER HUNTER #6H   - LAVACA',
 'PILSNER HUNTER #6H  - LAVACA',
 'PILSNER HUNTER #7H   - LAVACA',
 'PILSNER HUNTER #7H  - LAVACA',
 'PLATYPUS HUNTER #2H   - LAVACA',
 'PLATYPUS HUNTER #2H  - LAVACA',
 'PLATYPUS HUNTER #3H   - LAVACA',
 'PLATYPUS HUNTER #3H  - LAVACA',
 'PORCUPINE #1H   - LAVACA',
 'PORCUPINE #1H  - LAVACA',
 'PORTER #1H   - LAVACA',
 'PORTER #1H  - LAVACA',
 'Lavaca P Vade Von North',
 'PYRITE 1H   - LAVACA',
 'PYRITE 1H  - LAVACA',
 'Lavaca Rabbfojtik 1H 2H CT LP',
 'Lavaca Rabbfojtik 1H 2H CT',
 'Lavaca Rattler CT',
 'Lavaca Rattler CT LPR',
 'RBK #1H CLOICE   - LAVACA',
 'RBK #1H CLOICE  - LAVACA',
 'RBK #2 MARL   - LAVACA',
 'RBK #2 MARL  - LAVACA',
 'RBK #3H CLOICE   - LAVACA',
 'RBK #3H CLOICE  - LAVACA',
 'RBK #4H MARL   - LAVACA',
 'RBK #4H MARL  - LAVACA',
 'Lavaca RCR East CT GL',
 'Lavaca RCR East CT LPR',
 'Lavaca RCR West CT GL',
 'Lavaca RCR West CT LPR',
 'REFFENSHACK A 1H   - LAVACA',
 'REFFENSHACK A 1H  - LAVACA',
 'REFFENSHACK B 2H   - LAVACA',
 'REFFENSHACK B 2H  - LAVACA',
 'REFFENSHACK C 3H   - LAVACA',
 'REFFENSHACK C 3H  - LAVACA',
 'Lavaca Rhino Hunter CT',
 'RHINOSTONE 1H   - LAVACA',
 'RHINOSTONE 1H  - LAVACA',
 'RIGBY UNIT 2H   - LAVACA',
 'RIGBY UNIT 2H  - LAVACA',
 'RIGBY UNIT 3H   - LAVACA',
 'RIGBY UNIT 3H  - LAVACA',
 'RIGBY UNIT 4H   - LAVACA',
 'RIGBY UNIT 4H  - LAVACA',
 'Lavaca Rigby Lott CT',
 'Lavaca Rigby Lott CT LPR',
 'RIO LAVACA #1H   - LAVACA',
 'RIO LAVACA #1H  - LAVACA',
 'RIO LAVACA #2H   - LAVACA',
 'RIO LAVACA #2H  - LAVACA',
 'ROCK CREEK #10H   - LAVACA',
 'ROCK CREEK #10H  - LAVACA',
 'ROCK CREEK RANCH 18H   - LAVACA',
 'ROCK CREEK RANCH 18H  - LAVACA',
 'ROCK CREEK RANCH #20   - LAVACA',
 'ROCK CREEK RANCH #20  - LAVACA',
 'ROCK CREEK #9H   - LAVACA',
 'ROCK CREEK #9H  - LAVACA',
 'SABLE HUNTER #4H   - LAVACA',
 'SABLE HUNTER #4H  - LAVACA',
 'SABLE HUNTER #5H   - LAVACA',
 'SABLE HUNTER #5H  - LAVACA',
 'SABLE HUNTER #6H   - LAVACA',
 'SABLE HUNTER #6H  - LAVACA',
 'Lavaca Sanchez A',
 'Lavaca Sanchez B',
 'Lavaca Sanchez Moulton',
 'SAPPHIRE A1H   - LAVACA',
 'SAPPHIRE A1H  - LAVACA',
 'SAPPHIRE B 2H   - LAVACA',
 'SAPPHIRE B 2H  - LAVACA',
 'SCHACHERL-EFFENBERGER (SA) UNIT 3H   - LAVACA',
 'SCHACHERL-EFFENBERGER (SA) UNIT 3H  - LAVACA',
 'SCHACHERL-EFFENBERGER (SA) UNIT 4H   - LAVACA',
 'SCHACHERL-EFFENBERGER (SA) UNIT 4H  - LAVACA',
 'SERPENTINE A 1H   - LAVACA',
 'SERPENTINE A 1H  - LAVACA',
 'SERPENTINE B 2H   - LAVACA',
 'SERPENTINE B 2H  - LAVACA',
 'SERPENTINE C 3H   - LAVACA',
 'SERPENTINE C 3H  - LAVACA',
 'SHINER RANCH-S HUNTER SA 1 1H   - LAVACA',
 'SHINER RANCH-S HUNTER SA 1 1H  - LAVACA',
 'SHINER RANCH-S HUNTER SA 2 2H   - LAVACA',
 'SHINER RANCH-S HUNTER SA 2 2H  - LAVACA',
 'Lavaca Shiner Ranch CT',
 'SNIPE HUNTER #1H   - LAVACA',
 'SNIPE HUNTER #1H  - LAVACA',
 'SNIPE 3H   - LAVACA',
 'SNIPE 3H  - LAVACA',
 'SNIPE 4H   - LAVACA',
 'SNIPE 4H  - LAVACA',
 'SNIPE 5H   - LAVACA',
 'SNIPE 5H  - LAVACA',
 'SOUTHERN HUNTER AMBER #1H   - LAVACA',
 'SOUTHERN HUNTER AMBER #1H  - LAVACA',
 'SOUTHERN HUNTER AMBER #2H   - LAVACA',
 'SOUTHERN HUNTER AMBER #2H  - LAVACA',
 'Lavaca Southern Hunter CT',
 'TOPAZ A 1H   - LAVACA',
 'TOPAZ A 1H  - LAVACA',
 'TOPAZ B 2H   - LAVACA',
 'TOPAZ B 2H  - LAVACA',
 'TOPAZ C 3H   - LAVACA',

In [44]:
no_nan_rows = outer_join_01[outer_join_01.notna().all(axis=1)]
no_nan_rows

,item_id,point_name,equipment,parent_equipment_name,equipment_type,Name,Accounting Number
0,10000.0,Tubing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H,204600.01
1,10001.0,Casing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H,204600.01
2,11245.0,Injection Rate Setpoint,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H,204600.01
3,11247.0,ESD Valve Status,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H,204600.01
4,62085.0,Differential Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H,204600.01
...,...,...,...,...,...,...,...
28364,62831.0,Static Pressure,BUFFALO HUNTER #1H,BUFFALO HUNTER Well Pad,Gas Lift,BUFFALO HUNTER #1H,203220.01
28365,62832.0,Differential Pressure,GONZO HUNTER #1H,GONZO HUNTER Well Pad,Gas Lift,GONZO HUNTER #1H,203228.01
28366,62833.0,Static Pressure,GONZO HUNTER #1H,GONZO HUNTER Well Pad,Gas Lift,GONZO HUNTER #1H,203228.01
28367,62839.0,Differential Pressure,DEEDRA 1H,DEEDRA 1H Well Pad,Gas Lift,DEEDRA 1H,204425.01
28368,62840.0,Static Pressure,DEEDRA 1H,DEEDRA 1H Well Pad,Gas Lift,DEEDRA 1H,204425.01

##### Adding new column as Well Name which is basically a copy of the equipment in the lookup file

In [7]:
lookup['well_name'] = lookup['equipment']
lookup

,item_id,point_name,equipment,parent_equipment_name,equipment_type,well_name
0,10000,Tubing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H
1,10001,Casing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H
2,10002,Tubing Pressure,BIG FIVE B 2H,BIG FIVE Well Pad,Gas Lift,BIG FIVE B 2H
3,10003,Casing Pressure,BIG FIVE B 2H,BIG FIVE Well Pad,Gas Lift,BIG FIVE B 2H
4,10004,Tubing Pressure,BLOODSTONE C 3H,BLOODSTONE C 3H D 4H Well Pad,Gas Lift,BLOODSTONE C 3H
...,...,...,...,...,...,...
28454,71106,PLC Battery Voltage,PECAN Facility,NaN,Facility,PECAN Facility
28455,71107,PLC Battery Voltage,MATOCHA 1H Facility,NaN,Facility,MATOCHA 1H Facility
28456,71108,PLC Battery Voltage,COLLEEN CALYPSO Facility,NaN,Facility,COLLEEN CALYPSO Facility
28457,71109,PLC Battery Voltage,HAWKEYE 9H 10H 11H Facility,NaN,Facility,HAWKEYE 9H 10H 11H Facility
28458,99999999,Tank Btm Level,10-23 Oil Tank 1,RANGER BEALL D-Pad Tank Battery,Storage,10-23 Oil Tank 1

In [8]:
import re

unwanted_strings = [
    'Water Meter', 'Oil Meter', 'Oil Tank 1', 'Gas Lift Meter', 'Water Tank'
    'Production Meter', 'Reject Tank', 'Oil Tank 2', 'Oil Tank 3', 'Water Tank #1', 'Water Tank #2',
    'Water Tank #3', 'Water Tank #4', 'Water Tank #5', 'Water Tank #6', 'Oil(Reject) Tank #5'
    'Oil Tank 4', 'Oil Tank 5', 'Meter', 'HP Meter', 'Jet Pump', 'Gas Lift', 'Drip Tank', 'Lact'
    'Remote Device', 'Oil Tank', 'Water Tank 1', 'Water Tank 2', 'Water Tank 3'
    'Cooler Scrubber', 'Separator', 'Fuel Scrubber', 'Oil(Reject) Tank #5'
    'Flare Scrubber', 'Facility', 'Flash Gas', 'Tank Battery', 'Heater Separator',
    'Heater Treater', 'Flare', 'Production', 'Water Test Tank', 'Water Common Tank',
    'Oil Test Tank', 'Oil Common Tank', 'Seperator', 'Bulk', 'Tank 1', 'Tank 2',
    'Oil Common Tank', 'Water Test Tank', 'Common', 'Production', 'Injection',
    'Compressor Discharge', 'Compressor Fuel Gas', 'Sales Check', 'Sales', 'Robin',
    'Unknown', 'Unknown Tank 3', 'Unknown Tank 4', 'Unknown Tank 5', 'Unknown Tank 6',
    'Unknown Tank 7', 'Unknown Tank 8', 'Water Tank', 'Remove Device', 'Cooler Scrubber', 'Scrubber',
    'Fuel', 'Tank', 'Water Tank #1', 'Water Tank #2', '#1', '#2', '#3', '#4', '#6', '#5', 'Gas Lift'
]

pattern = '|'.join(map(re.escape, unwanted_strings))
lookup['well_name'] = lookup['well_name'].str.replace(pattern, '', regex=True).str.strip()

In [15]:
lookup.to_csv('updated_lookup.csv', index=False)

##### Outer join with the well_name of look_up file and Name in Iron_Iq file

In [11]:
# outer_join_02 = pd.merge(lookup, iron_iQ, left_on='well_name', right_on='Name', how='outer')
# outer_join_02

outer_join_02 = pd.merge(lookup, iron_iQ, left_on='well_name', right_on='Name', how='left')
outer_join_02

,item_id,point_name,equipment,parent_equipment_name,equipment_type,well_name,Name,Accounting Number
0,10000,Tubing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H,BIG FIVE A1 H,204600.01
1,10001,Casing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H,BIG FIVE A1 H,204600.01
2,10002,Tubing Pressure,BIG FIVE B 2H,BIG FIVE Well Pad,Gas Lift,BIG FIVE B 2H,BIG FIVE B 2H,204601.01
3,10003,Casing Pressure,BIG FIVE B 2H,BIG FIVE Well Pad,Gas Lift,BIG FIVE B 2H,BIG FIVE B 2H,204601.01
4,10004,Tubing Pressure,BLOODSTONE C 3H,BLOODSTONE C 3H D 4H Well Pad,Gas Lift,BLOODSTONE C 3H,BLOODSTONE C 3H,204686.01
...,...,...,...,...,...,...,...,...
28454,71106,PLC Battery Voltage,PECAN Facility,NaN,Facility,PECAN,NaN,NaN
28455,71107,PLC Battery Voltage,MATOCHA 1H Facility,NaN,Facility,MATOCHA 1H,MATOCHA 1H,204666.01
28456,71108,PLC Battery Voltage,COLLEEN CALYPSO Facility,NaN,Facility,COLLEEN CALYPSO,NaN,NaN
28457,71109,PLC Battery Voltage,HAWKEYE 9H 10H 11H Facility,NaN,Facility,HAWKEYE 9H 10H 11H,NaN,NaN
28458,99999999,Tank Btm Level,10-23 Oil Tank 1,RANGER BEALL D-Pad Tank Battery,Storage,10-23,NaN,NaN

In [12]:
name_nan_rows = outer_join_02[outer_join_02['Accounting Number'].isna()]
name_nan_rows

,item_id,point_name,equipment,parent_equipment_name,equipment_type,well_name,Name,Accounting Number
54,10054,Tubing Pressure,EFFENBERGER #4H,EFFENBERGER Well Pad,Gas Lift,EFFENBERGER H,NaN,NaN
55,10055,Casing Pressure,EFFENBERGER #4H,EFFENBERGER Well Pad,Gas Lift,EFFENBERGER H,NaN,NaN
56,10056,Tubing Pressure,EFFENBERGER #5H,EFFENBERGER Well Pad,Gas Lift,EFFENBERGER H,NaN,NaN
57,10057,Casing Pressure,EFFENBERGER #5H,EFFENBERGER Well Pad,Gas Lift,EFFENBERGER H,NaN,NaN
62,10062,Tubing Pressure,ROCK CREEK #11H,ROCK CREEK RANCH Well Pad,Gas Lift,ROCK CREEK 1H,NaN,NaN
...,...,...,...,...,...,...,...,...
28453,71105,PLC Battery Voltage,TIGERS EYE Facility,NaN,Facility,TIGERS EYE,NaN,NaN
28454,71106,PLC Battery Voltage,PECAN Facility,NaN,Facility,PECAN,NaN,NaN
28456,71108,PLC Battery Voltage,COLLEEN CALYPSO Facility,NaN,Facility,COLLEEN CALYPSO,NaN,NaN
28457,71109,PLC Battery Voltage,HAWKEYE 9H 10H 11H Facility,NaN,Facility,HAWKEYE 9H 10H 11H,NaN,NaN
28458,99999999,Tank Btm Level,10-23 Oil Tank 1,RANGER BEALL D-Pad Tank Battery,Storage,10-23,NaN,NaN

In [13]:
a = list(name_nan_rows['well_name'].unique())
b = len(a)
a

['EFFENBERGER H',
 'ROCK CREEK 1H',
 'PLATYPUS HUNTER H',
 'BLOODSTONE D H',
 'CINCO RANCH E H',
 'Pyrtie 1H',
 'MAMMOTH B 2H',
 'LOMBARDO H',
 'PILSNER HUNTER H',
 'BIG FIVE',
 'BIG FIVE  4',
 'CARBONITE',
 'EMERALD',
 'EMERALD  4',
 'HALITE',
 'HAWN HOLT/PYRITE',
 'HAWN HOLT/PYRITE  4',
 'LABRADORITE',
 'LABRADORITE  4',
 'MAMMOTH',
 'MAMMOTH   3',
 'MAMMOTH   4',
 'MAMMOTH   5',
 'MAMMOTH   6',
 'MAMMOTH   7',
 'MAMMOTH   8',
 'MOONSTONE',
 'MOONSTONE  4',
 'RATTLER',
 'DIAMOND LAGER',
 'SAPPHIRE',
 'SAPPHIRE  4',
 'SAPPHIRE  6',
 'SHARKTOOTH',
 'BRUCITE/KOSMO/PORTER',
 'QUARTZ',
 'BIG FIVE Remote Device',
 'BLOODSTONE Remote Device',
 'CARBONITE Remote Device',
 'CORAL Remote Device',
 'DIAMOND Remote Device',
 'DRAGONSTONE',
 'EMERALD Remote Device',
 'HALITE Remote Device',
 'HAWN HOLT Remote Device',
 'LABRADORITE Remote Device',
 'MAMMOTH Remote Device',
 'MOONSTONE Remote Device',
 'RATTLER Remote Device',
 'ROCK CREEK RANCH QUARTZ Remote Device',
 'SAPPHIRE Remote Device',
 'SERPENTINE Remote Device',
 'SHARKTOOTH Remote Device',
 'TOPAZ Remote Device',
 'TURQUOISE Remote Device',
 'KYBER Remote Device',
 'MAMMOTH Well 1 LACT',
 'MAMMOTH Well 2 LACT',
 'MAMMOTH LACT',
 nan,
 'WAVELLITE/WOMBAT',
 'WAVELLITE/WOMBAT  4',
 'WAVELLITE/WOMBAT Remote Device',
 'HAWN HOLT 2H',
 'HAWN HOLT 8H',
 'HAWN HOLT 3H',
 'HAWN HOLT/TREMOLITE LACT',
 'HAWN HOLT/TREMOLITE',
 'HAWN HOLT/TREMOLITE Remote Device',
 'B.S C3D4/ZIRCON',
 'CAROL ROBINS',
 'B.S C3D4/ZIRCON LACT 3',
 'CAROL ROBINS LACT 1',
 'CAROL ROBINS LACT 3',
 'ZIRCON/CAROL  LACT',
 'ZIRCON/CAROL  Remote Device',
 'R.WASHINGTON H',
 'BOWIE H',
 'BOWIE H-WASHINGTON CT LPR',
 'BOWIE H-WASHINGTON CT',
 'AQUAMARINE/BOWIE/WASHINGTON  4',
 'AQUAMARINE/BOWIE/WASHINGTON',
 'KOSMO H',
 'PORTER H',
 'HAWN HOLT/TREMOLITE  Remote Device',
 'AQUAMARINE/BOWIE/WASHINGTON Remote Device',
 'CINNABAR Remote Device',
 'NEVELS ADDAX NAB HUNTER Addax Remote Device',
 'ADDAX HUNTER H',
 'MOONSTONE VRU',
 'WHITE OAK',
 'WHITE OAK B2H LP',
 'WHITE OAK B2H HP',
 'WHITE OAK A1H HP',
 'WHITE OAK A1H LP',
 'WHITE OAK LP',
 'WHITE OAK HP',
 'WHITE OAK LP  Remote Device',
 'WHITE OAK B2H LP Remote Device',
 'WHITE OAK B2H HP Remote Device',
 'WHITE OAK A1H HP Remote Device',
 'WHITE OAK A1H LP Remote Device',
 'WHITE OAK HP  Remote Device',
 'WHITE OAK A1H Inj Remote Device',
 'WHITE OAK B2H Inj Remote Device',
 'EBONY/IVORY',
 'SOUTHERN HUNTER/AMBER',
 'SOUTHERN HUNTER AMBER H',
 'SHINER RANCH LPR',
 'SHINER RANCH CT',
 'SOUTHERN HUNTER/AMBER/EBONY/IVORY Remote Device',
 'DAWLEAN RICHARDSON',
 'DAWLEAN RICHARDSON   Remote Device',
 'DAWLEAN RICHARDSON UNIT 1H  Remote Device',
 'DAWLEAN RICHARDSON UNIT 2H  Remote Device',
 'DAWLEAN RICHARDSON Remote Device',
 'HAWN HOLT/RUTILE  6',
 'HAWN HOLT/RUTILE',
 'HAWN HOLT/RUTILE  4',
 'HAWN HOLT A1H B2H Remote Device',
 'RUTILE Remote Device',
 'WALNUT',
 'WALNUT B2H LP',
 'WALNUT B2H HP',
 'WALNUT A1H HP',
 'WALNUT A1H LP',
 'WALNUT HP',
 'WALNUT LP',
 'WALNUT Remote Device',
 'WALNUT HP   Remote Device',
 'WALNUT LP   Remote Device',
 'WALNUT A1H LP  Remote Device',
 'WALNUT A1H  Remote Device',
 'WALNUT B2H  Remote Device',
 'WALNUT B2H LP  Remote Device',
 'WALNUT B2H   Remote Device',
 'WALNUT A1H   Remote Device',
 'TestLab CLX Remote Device',
 'CANNONADE SPRINGS/AZURITE',
 'CANNONADE SPRINGS/AZURITE  4',
 'CANNONADE SPRINGS Remote Device',
 'AZURITE Remote Device',
 'CHARON/GATOR',
 'CHARON/GATOR  4',
 'GATOR H',
 'GATOR Remote Device',
 'CHARON Remote Device',
 'TREMOLITE  Remote Device',
 'HORNED G LP',
 'HORNED G LP  Remote Device',
 'HORNED H LP  Remote Device',
 'HORNED H LP',
 'WALNUT   Remote Device',
 'OPAL/MUNSON RANCH',
 'OPAL/MUNSON RANCH Remote Device',
 'GEORG EF/Maple',
 'MAPLE A1H',
 'MAPLE B2H',
 'Pump',
 'ADDAX HUNTER 6H  - LAVACA',
 'ADDAX HUNTER #7H  - LAVACA',
 'ADDAX HUNTER #8H  - LAVACA',
 'ADDAX HUNTER H   - LAVACA',
 'ADDAX HUNTER H  - LAVACA',
 'ADDAX HUNTER 3H   - LAVACA',
 'ADDAX HUNTER 3H  - LAVACA',
 'ADDAX HUNTER 6H   - LAVACA',
 'ADDAX HUNTER #7H   - LAVACA',
 'ADDAX HUNTER #8H   - LAVACA',
 'AMBER H   - LAVACA',
 'AMBER H  - LAVACA',
 'AMBER-LAGER A (SA) 1H  - LAVACA',
 'AMBER-LAGER A (SA) 1H   - LAVACA',
 'AMBER-LAGER B (SA) 2H  - LAVACA',
 'AMBER-LAGER B (SA) 2H   - LAVACA',
 'Lavaca Amber Porter 2H 3H CT LPR',
 'Lavaca Amber Porter CT',
 'AMETHYST 1H   - LAVACA',
 'AMETHYST 1H  - LAVACA',
 'ANTEATER H   - LAVACA',
 'ANTEATER H  - LAVACA',
 'Lavaca Aquamarine CT',
 'Lavaca Aquamarine CT LPR',
 'ARLEDGE RANCH H   - LAVACA',
 'ARLEDGE RANCH H  - LAVACA',
 'ARMADILLO A (SA) 1H   - LAVACA',
 'ARMADILLO A (SA) 1H  - LAVACA',
 'ARMADILLO B (SA) 2H   - LAVACA',
 'ARMADILLO B (SA) 2H  - LAVACA',
 'ARMADILLO C (SA) 3H   - LAVACA',
 'ARMADILLO C (SA) 3H  - LAVACA',
 'AXIS H   - LAVACA',
 'AXIS H  - LAVACA',
 'AZURITE A1H   - LAVACA',
 'AZURITE B2H   - LAVACA',
 'BADGER H   - LAVACA',
 'BADGER H  - LAVACA',
 'BERTHA H   - LAVACA',
 'BERTHA H  - LAVACA',
 'BIG FIVE A1 H   - LAVACA',
 'BIG FIVE A1 H  - LAVACA',
 'BIG FIVE B 2H   - LAVACA',
 'BIG FIVE B 2H  - LAVACA',
 'BLONDE    - LAVACA',
 'BLONDE   - LAVACA',
 'BLONDE H   - LAVACA',
 'BLONDE H  - LAVACA',
 'BLONDE #7H   - LAVACA',
 'BLONDE #7H  - LAVACA',
 'BLONDE #8H   - LAVACA',
 'BLONDE #8H  - LAVACA',
 'BLONDE #9H   - LAVACA',
 'BLONDE #9H  - LAVACA',
 'BLOODSTONE C 3H   - LAVACA',
 'BLOODSTONE C 3H  - LAVACA',
 'BLOODSTONE D 4H   - LAVACA',
 'BLOODSTONE D 4H  - LAVACA',
 'BOCK H   - LAVACA',
 'BOCK H  - LAVACA',
 'BONGO HUNTER H   - LAVACA',
 'BONGO HUNTER H  - LAVACA',
 'Lavaca Bongo Hunter CT',
 'Lavaca Bongo Hunter CT LPR',
 'BONGO SOUTH H   - LAVACA',
 'BONGO SOUTH H  - LAVACA',
 'Lavaca Bongo Stag CT',
 'Lavaca Bongo Stag CT LPR',
 'Lavaca Bowie Washington CT',
 'Lavaca Bowie Washington CT LPR',
 'BRUCITE A1H   - LAVACA',
 'BRUCITE A1H  - LAVACA',
 'BRUCITE B2H   - LAVACA',
 'BRUCITE B2H  - LAVACA',
 'BUFFALO HUNTER H   - LAVACA',
 'BUFFALO HUNTER H  - LAVACA',
 'Lavaca Cannonade Springs CT',
 'Lavaca Cannonade Springs CT LPR',
 'CARACARA UNIT 1H   - LAVACA',
 'CARACARA UNIT 1H  - LAVACA',
 'CARACARA UNIT 2H   - LAVACA',
 'CARACARA UNIT 2H  - LAVACA',
 'CARACARA UNIT 4H   - LAVACA',
 'CARACARA UNIT 4H  - LAVACA',
 'CARBONITE A1H   - LAVACA',
 'CARBONITE A1H  - LAVACA',
 'CARBONITE B2H   - LAVACA',
 'CARBONITE B2H  - LAVACA',
 'CARBONITE C3H   - LAVACA',
 'CARBONITE C3H  - LAVACA',
 'CAROL-ROBIN (SA) UNIT 1 1H   - LAVACA',
 'CAROL-ROBIN (SA) UNIT 1 1H  - LAVACA',
 'CAROL-ROBIN (SA) UNIT 2 2H   - LAVACA',
 'CAROL-ROBIN (SA) UNIT 2 2H  - LAVACA',
 'CHARON A1H   - LAVACA',
 'CHARON B2H   - LAVACA',
 'CHICKEN HAWK H   - LAVACA',
 'CHICKEN HAWK H  - LAVACA',
 'Lavaca Chickenhawk CT',
 'CINCO RANCH E H   - LAVACA',
 'CINCO RANCH E H  - LAVACA',
 'CINCO J RANCH LTD H    - LAVACA',
 'CINCO J RANCH LTD H   - LAVACA',
 'CINCO J RANCH LTD UNIT 2H   - LAVACA',
 'CINCO J RANCH LTD UNIT 2H  - LAVACA',
 'Lavaca Cinco J Ranch CT',
 'Lavaca Cinco J Ranch CT LPR',
 'CINNABAR A 1H   - LAVACA',
 'CINNABAR A 1H  - LAVACA',
 'CINNABAR B 2H   - LAVACA',
 'CINNABAR B 2H  - LAVACA',
 'COYOTE A (SA) 1H   - LAVACA',
 'COYOTE A (SA) 1H  - LAVACA',
 'COYOTE B (SA) 2H   - LAVACA',
 'COYOTE B (SA) 2H  - LAVACA',
 'CROC H   - LAVACA',
 'CROC H  - LAVACA',
 'DEEDRA-LORI (SA) UNIT 3 3H   - LAVACA',
 'DEEDRA-LORI (SA) UNIT 3 3H  - LAVACA',
 'DEEDRA-LORI (SA) UNIT 4 4H   - LAVACA',
 'DEEDRA-LORI (SA) UNIT 4 4H  - LAVACA',
 'DIAMOND A1H   - LAVACA',
 'DIAMOND A1H  - LAVACA',
 'DINGO HUNTER H   - LAVACA',
 'DINGO HUNTER H  - LAVACA',
 'Lavaca Dingo Platypus CT',
 'Lavaca Dingo Platypus CT LPR',
 'DICKSON ALLEN H (Devon)   - LAVACA',
 'DICKSON ALLEN H (Devon)  - LAVACA',
 'Lavaca Douglas Raab CT',
 'Lavaca Douglas Raab CT LP',
 'DRAGONSTONE A 1H   - LAVACA',
 'DRAGONSTONE A 1H  - LAVACA',
 'DRAGONSTONE B 2H   - LAVACA',
 'DRAGONSTONE B 2H  - LAVACA',
 'EBONY 1H   - LAVACA',
 'EBONY 1H  - LAVACA',
 'EFFENBERGER H   - LAVACA',
 'EFFENBERGER H  - LAVACA',
 'EFFENBERGER-SCHACHERL H   - LAVACA',
 'EFFENBERGER-SCHACHERL H  - LAVACA',
 'ELK HUNTER H   - LAVACA',
 'ELK HUNTER H  - LAVACA',
 'EMERALD A1H   - LAVACA',
 'EMERALD A1H  - LAVACA',
 'EMERALD B2H   - LAVACA',
 'EMERALD B2H  - LAVACA',
 'RCR FLETCHER    - LAVACA',
 'RCR FLETCHER   - LAVACA',
 'FURRH 4H   - LAVACA',
 'FURRH 4H  - LAVACA',
 'FURRH 5H   - LAVACA',
 'FURRH 5H  - LAVACA',
 'GARNET 1H   - LAVACA',
 'GARNET 1H  - LAVACA',
 'GATOR H   - LAVACA',
 'GATOR H  - LAVACA',
 'GEO HUNTER H   - LAVACA',
 'GEO HUNTER H  - LAVACA',
 'GOLDEN BEAR (SA) 1H   - LAVACA',
 'GOLDEN BEAR (SA) 1H  - LAVACA',
 'GONZO HUNTER H   - LAVACA',
 'GONZO HUNTER H  - LAVACA',
 'GONZO NORTH #7H   - LAVACA',
 'GONZO NORTH #7H  - LAVACA',
 'GONZO NORTH #8H   - LAVACA',
 'GONZO NORTH #8H  - LAVACA',
 'GONZO NORTH #9H   - LAVACA',
 'GONZO NORTH #9H  - LAVACA',
 'Lavaca Gonzos Buffalo H CT GL',
 'Lavaca Gonzos Buffalo H CT LPR',
 'HALITE A1H   - LAVACA',
 'Lavaca Halite/Ceres CT GL',
 'HALITE B2H   - LAVACA',
 'HAWG HUNTER H   - LAVACA',
 'HAWG HUNTER H  - LAVACA',
 'Lavaca Hawnda CT',
 'Lavaca Hawnda CT LPR',
 'HAWN HOLT 3H   - LAVACA',
 'HAWN HOLT 3H  - LAVACA',
 'HAWN HOLT 6   - LAVACA',
 'HAWN HOLT 6  - LAVACA',
 'HAWN HOLT 7   - LAVACA',
 'HAWN HOLT 7  - LAVACA',
 'Lavaca Hawn Holt 1819 CT',
 'HAWN HOLT 21H   - LAVACA',
 'HAWN HOLT 21H  - LAVACA',
 'HAWN HOLT H   - LAVACA',
 'HAWN HOLT H  - LAVACA',
 'Lavaca Hawn Holt CT',
 'Lavaca Hawn Holt CT LPR',
 'Lavaca Heatwave Leal CT',
 'Lavaca Heatwave Leal CT LPR',
 'HEDGEHOG H   - LAVACA',
 'HEDGEHOG H  - LAVACA',
 'Lavaca Hinze CT',
 'Lavaca Hinze CT LPR',
 'HIPPO HUNTER 3H   - LAVACA',
 'HIPPO HUNTER 3H  - LAVACA',
 'HIPPO HUNTER H   - LAVACA',
 'HIPPO HUNTER H  - LAVACA',
 'IVORY 1H   - LAVACA',
 'IVORY 1H  - LAVACA',
 'Lavaca Jackalope CT',
 'Lavaca Jackelope 1H 2H LP CT',
 'JAKE BERGER CATTLE H   - LAVACA',
 'JAKE BERGER CATTLE H  - LAVACA',
 'JAKE BERGER CATTLE CO 2H   - LAVACA',
 'JAKE BERGER CATTLE CO 2H  - LAVACA',
 'JAKE BERGER CATTLE CO 4H   - LAVACA',
 'JAKE BERGER CATTLE CO 4H  - LAVACA',
 'JAKE BERGER CATTLE CO 5H   - LAVACA',
 'JAKE BERGER CATTLE CO 5H  - LAVACA',
 'Lavaca Jake Berger Jr CT',
 'RCR JANE    - LAVACA',
 'RCR JANE   - LAVACA',
 'RCRS JANE H   - LAVACA',
 'RCRS JANE H  - LAVACA',
 'RCRS JANE #7H   - LAVACA',
 'RCRS JANE #7H  - LAVACA',
 'JEFFERY UNIT H   - LAVACA',
 'JEFFERY UNIT H  - LAVACA',
 'JOSEPH SIMPER H   - LAVACA',
 'JOSEPH SIMPER H  - LAVACA',
 'KOSMO H   - LAVACA',
 'KOSMO H  - LAVACA',
 'KUDU HUNTER H   - LAVACA',
 'KUDU HUNTER H  - LAVACA',
 'KUDU HUNTER #7H   - LAVACA',
 'KUDU HUNTER #7H  - LAVACA',
 'KUDU HUNTER #8H   - LAVACA',
 'KUDU HUNTER #8H  - LAVACA',
 'KUDU HUNTER #9H   - LAVACA',
 'KUDU HUNTER #9H  - LAVACA',
 'KUSAK H   - LAVACA',
 'KUSAK H  - LAVACA',
 'LABRADORITE A 1H   - LAVACA',
 'LABRADORITE A 1H  - LAVACA',
 'LABRADORITE B 2H   - LAVACA',
 'LABRADORITE B 2H  - LAVACA',
 'LABRADORITE C 3H   - LAVACA',
 'LABRADORITE C 3H  - LAVACA',
 'LAGER H   - LAVACA',
 'LAGER H  - LAVACA',
 'LAGER UNIT 4H   - LAVACA',
 'LAGER UNIT 4H  - LAVACA',
 'LEOPARD HUNTER H   - LAVACA',
 'LEOPARD HUNTER H  - LAVACA',
 'LEOPARD HUNTER #7H   - LAVACA',
 'LEOPARD HUNTER #7H  - LAVACA',
 'L & LEE UNIT 7H   - LAVACA',
 'L & LEE UNIT 7H  - LAVACA',
 'Lavaca LJ Lee CT',
 'Lavaca LJ Lee RCR Manning 1H',
 'Lavaca LJ Lee RCR Manning 2H',
 'LOTT 5H   - LAVACA',
 'LOTT 5H  - LAVACA',
 'LOTT 6H   - LAVACA',
 'LOTT 6H  - LAVACA',
 'LOTT 7H   - LAVACA',
 'LOTT 7H  - LAVACA',
 'Lavaca Mammoth Lm CT',
 'Lavaca Mammoth Lm CT LPR',
 'MARCIA-SHELLY (SA) UNIT 1 1H   - LAVACA',
 'MARCIA-SHELLY (SA) UNIT 1 1H  - LAVACA',
 'MARCIA-SHELLY (SA) UNIT 2 2H   - LAVACA',
 'MARCIA-SHELLY (SA) UNIT 2 2H  - LAVACA',
 'MATIAS H   - LAVACA',
 'MATIAS H  - LAVACA',
 'Lavaca Mccreary Javelina CT',
 'Lavaca Mccreary Javelina CT LPR',
 'Lavaca Mccreary Technik CT Hp',
 'Lavaca Mccreay Technik CT LPR',
 'MOONSTONE A1H   - LAVACA',
 'MOONSTONE A1H  - LAVACA',
 'MOONSTONE B2H   - LAVACA',
 'MOONSTONE B2H  - LAVACA',
 'MOOSE HUNTER H   - LAVACA',
 'MOOSE HUNTER H  - LAVACA',
 'MUNSON RANCH 13H   - LAVACA',
 'MUNSON RANCH 13H  - LAVACA',
 'MUNSON RANCH 14H   - LAVACA',
 'MUNSON RANCH 14H  - LAVACA',
 'MUNSON RANCH 15H   - LAVACA',
 'MUNSON RANCH 15H  - LAVACA',
 'MUNSON RANCH 9H   - LAVACA',
 'MUNSON RANCH 9H  - LAVACA',
 'MUNSON RANCH 24H   - LAVACA',
 'MUNSON RANCH 24H  - LAVACA',
 'NAB HUNTER 1H   - LAVACA',
 'NAB HUNTER 1H  - LAVACA',
 'NEVELS ADDAX 1H   - LAVACA',
 'NEVELS ADDAX 1H  - LAVACA',
 'Nitro B 3H   - LAVACA',
 'Nitro B 3H  - LAVACA',
 'Nitro B 4H   - LAVACA',
 'Nitro B 4H  - LAVACA',
 'O BORCHERS E H   - LAVACA',
 'O BORCHERS E H  - LAVACA',
 'OPAL 1H   - LAVACA',
 'OPAL 1H  - LAVACA',
 'ORYX HUNTER H   - LAVACA',
 'ORYX HUNTER H  - LAVACA',
 'Lavaca Oryx Furr H CT',
 'Lavaca Oryx Furr H CT LPR',
 'PILSNER HUNTER H   - LAVACA',
 'PILSNER HUNTER H  - LAVACA',
 'PILSNER HUNTER #7H   - LAVACA',
 'PILSNER HUNTER #7H  - LAVACA',
 'PLATYPUS HUNTER H   - LAVACA',
 'PLATYPUS HUNTER H  - LAVACA',
 'PORCUPINE H   - LAVACA',
 'PORCUPINE H  - LAVACA',
 'PORTER H   - LAVACA',
 'PORTER H  - LAVACA',
 'Lavaca P Vade Von North',
 'PYRITE 1H   - LAVACA',
 'PYRITE 1H  - LAVACA',
 'Lavaca Rabbfojtik 1H 2H CT LP',
 'Lavaca Rabbfojtik 1H 2H CT',
 'Lavaca Rattler CT',
 'Lavaca Rattler CT LPR',
 'RBK H CLOICE   - LAVACA',
 'RBK H CLOICE  - LAVACA',
 'RBK  MARL   - LAVACA',
 'RBK  MARL  - LAVACA',
 'RBK H MARL   - LAVACA',
 'RBK H MARL  - LAVACA',
 'Lavaca RCR East CT GL',
 'Lavaca RCR East CT LPR',
 'Lavaca RCR West CT GL',
 'Lavaca RCR West CT LPR',
 'REFFENSHACK A 1H   - LAVACA',
 'REFFENSHACK A 1H  - LAVACA',
 'REFFENSHACK B 2H   - LAVACA',
 'REFFENSHACK B 2H  - LAVACA',
 'REFFENSHACK C 3H   - LAVACA',
 'REFFENSHACK C 3H  - LAVACA',
 'Lavaca Rhino Hunter CT',
 'RHINOSTONE 1H   - LAVACA',
 'RHINOSTONE 1H  - LAVACA',
 'RIGBY UNIT 2H   - LAVACA',
 'RIGBY UNIT 2H  - LAVACA',
 'RIGBY UNIT 3H   - LAVACA',
 'RIGBY UNIT 3H  - LAVACA',
 'RIGBY UNIT 4H   - LAVACA',
 'RIGBY UNIT 4H  - LAVACA',
 'Lavaca Rigby Lott CT',
 'Lavaca Rigby Lott CT LPR',
 'RIO LAVACA H   - LAVACA',
 'RIO LAVACA H  - LAVACA',
 'ROCK CREEK 0H   - LAVACA',
 'ROCK CREEK 0H  - LAVACA',
 'ROCK CREEK RANCH 18H   - LAVACA',
 'ROCK CREEK RANCH 18H  - LAVACA',
 'ROCK CREEK RANCH 0   - LAVACA',
 'ROCK CREEK RANCH 0  - LAVACA',
 'ROCK CREEK #9H   - LAVACA',
 'ROCK CREEK #9H  - LAVACA',
 'SABLE HUNTER H   - LAVACA',
 'SABLE HUNTER H  - LAVACA',
 'Lavaca Sanchez A',
 'Lavaca Sanchez B',
 'Lavaca Sanchez Moulton',
 'SAPPHIRE A1H   - LAVACA',
 'SAPPHIRE A1H  - LAVACA',
 'SAPPHIRE B 2H   - LAVACA',
 'SAPPHIRE B 2H  - LAVACA',
 'SCHACHERL-EFFENBERGER (SA) UNIT 3H   - LAVACA',
 'SCHACHERL-EFFENBERGER (SA) UNIT 3H  - LAVACA',
 'SCHACHERL-EFFENBERGER (SA) UNIT 4H   - LAVACA',
 'SCHACHERL-EFFENBERGER (SA) UNIT 4H  - LAVACA',
 'SERPENTINE A 1H   - LAVACA',
 'SERPENTINE A 1H  - LAVACA',
 'SERPENTINE B 2H   - LAVACA',
 'SERPENTINE B 2H  - LAVACA',
 'SERPENTINE C 3H   - LAVACA',
 'SERPENTINE C 3H  - LAVACA',
 'SHINER RANCH-S HUNTER SA 1 1H   - LAVACA',
 'SHINER RANCH-S HUNTER SA 1 1H  - LAVACA',
 'SHINER RANCH-S HUNTER SA 2 2H   - LAVACA',
 'SHINER RANCH-S HUNTER SA 2 2H  - LAVACA',
 'Lavaca Shiner Ranch CT',
 'SNIPE HUNTER H   - LAVACA',
 'SNIPE HUNTER H  - LAVACA',
 'SNIPE 3H   - LAVACA',
 'SNIPE 3H  - LAVACA',
 'SNIPE 4H   - LAVACA',
 'SNIPE 4H  - LAVACA',
 'SNIPE 5H   - LAVACA',
 'SNIPE 5H  - LAVACA',
 'SOUTHERN HUNTER AMBER H   - LAVACA',
 'SOUTHERN HUNTER AMBER H  - LAVACA',
 'Lavaca Southern Hunter CT',
 'TOPAZ A 1H   - LAVACA',
 'TOPAZ A 1H  - LAVACA',
 'TOPAZ B 2H   - LAVACA',
 'TOPAZ B 2H  - LAVACA',
 'TOPAZ C 3H   - LAVACA',
 'TOPAZ C 3H  - LAVACA',
 'TREMOLITE A1H   - LAVACA',
 'TREMOLITE A1H  - LAVACA',
 'TREMOLITE B2H   - LAVACA',
 'TREMOLITE B2H  - LAVACA',
 'TURQUOISE A 1H   - LAVACA',
 'TURQUOISE A 1H  - LAVACA',
 'TURQUOISE B 2H   - LAVACA',
 'TURQUOISE B 2H  - LAVACA',
 'TURQUOISE C 3H   - LAVACA',
 'TURQUOISE C 3H  - LAVACA',
 'VANA-SMITH (SA) UNIT 1 1H   - LAVACA',
 'VANA-SMITH (SA) UNIT 1 1H  - LAVACA',
 'VANA-SMITH (SA) UNIT 2 2H   - LAVACA',
 'VANA-SMITH (SA) UNIT 2 2H  - LAVACA',
 'WOMBAT H  - LAVACA',
 'WOMBAT H   - LAVACA',
 'Lavaca Wombat Stag CT',
 'Lavaca Wombat Stag CT LPR',
 'YOUNG 1H   - LAVACA',
 'YOUNG 1H  - LAVACA',
 'ZEBRA HUNTER H   - LAVACA',
 'ZEBRA HUNTER H  - LAVACA',
 'ZEBRA HUNTER #7H   - LAVACA',
 'ZEBRA HUNTER #7H  - LAVACA',
 'ZIRCON A1H   - LAVACA',
 'ZIRCON A1H  - LAVACA',
 'ZIRCON B2H   - LAVACA',
 'ZIRCON B2H  - LAVACA',
 'OBSIDIAN A1H   - LAVACA',
 'OBSIDIAN B2H   - LAVACA',
 'SCHACHERL-VANA 2H 3H CTL PR',
 'SCHACHERL-VANA 2H 3H CT',
 'CANNONADE RANCH 7H   - LAVACA',
 'CANNONADE RANCH 8H  - LAVACA',
 'CANNONADE RANCH 9H  - LAVACA',
 'PV-1076',
 'SCHACHERL-VANA',
 'OBSIDIAN',
 'SCHACHERL-VANA H',
 'Lavaca Schacherl-Vana 2H-3H CT GL',
 'Lavaca Schacherl-Vana 2H-3H CT LPR',
 'SCHACHERL-VANA Remote Device',
 'OBSIDIAN Remote Device',
 'ROCK CREEK H   - LAVACA',
 'ROCK CREEK H  - LAVACA',
 'CARACARA/RICATORN',
 'CARACARA Remote Device',
 'RICARTORN Remote Device',
 'BONGO NORTH UNIT 3H   - LAVACA',
 'CERES A1H   - LAVACA',
 'CERES B2H   - LAVACA',
 'WALNUT G1H',
 'WALNUT G&H',
 'WALNUT H1H',
 'BONGO CERES Remote Device',
 'BONGO NORTH CERUS Lact',
 'BONGO NORTH CERUS',
 'Lavaca Dubose CT',
 'GARZA-KODACK H   - LAVACA',
 'GARZA-KODACK H  - LAVACA',
 'FLANE 1H   - LAVACA',
 'FLANE 1H  - LAVACA',
 'RCR JANE 5H   - LAVACA',
 'RCR JANE 5H  - LAVACA',
 'RCR JANE 8H   - LAVACA',
 'RCR JANE 8H  - LAVACA',
 'WELHAUSEN B H   - LAVACA',
 'WELHAUSEN B H  - LAVACA',
 'RCR JANE5H_8H_FLANE1H Remote Device',
 'GANYMEDE',
 'GANYMEDE Oil(Reject)',
 'GANYMEDE A1H HP',
 'GANYMEDE A1H LP',
 'GANYMEDE A1H LP  MCII',
 'GANYMEDE B2H HP',
 'GANYMEDE Remote Device',
 'Lavaca Cannonade Ranch',
 'Lavaca Gardner',
 'Lavaca Rock Creek Ranch',
 'Lavaca Shiner',
 'Lavaca Southern Hunter',
 'Lavaca Welhausen',
 'Lavaca Wombat /Check',
 'Lavaca Blond Comp Disch 1 Run 1',
 'Lavaca Blond Comp Disch 2 Run 1',
 'Lavaca Blond Comp Disch 3 Run 1',
 'Lavaca Cannonade Comp Disch 1 Run 1',
 'Lavaca Cannonade Comp Disch 2 Run 1',
 'Lavaca Gardner Comp Disch 1 Run 1',
 'Lavaca Geo Comp Disch 1 Run 1',
 'Lavaca Geo Comp Disch 2 Run 1',
 'Lavaca McCreary Comp Disch 1 Run 1',
 'Lavaca McCreary Comp Disch 2 Run 2',
 'Lavaca Miller Comp Disch 1 Run 1',
 'Lavaca Moose Comp Disch 1 Run 1',
 'Lavaca Munson Ranch Comp Disch 1',
 'Lavaca Munson Ranch Comp Disch 2 Run 2',
 'Lavaca RCR Wyatt Comp Disch 1 Run 1',
 'Lavaca Rock Creek Ranch Comp Disch 1 Run 1',
 'Lavaca Rock Creek Ranch Comp Disch 2 Run 2',
 'Lavaca Shiner Comp Disch 1 Run 1',
 'Lavaca Shiner Comp Disch 2 Run 1',
 'Lavaca Southern Hunter Comp Disch 1 Run 1',
 'Lavaca Southern Hunter Comp Disch 2 Run 1',
 'Lavaca Southern Hunter Comp Disch 3 Run 1',
 'Lavaca Wellhausen Comp Disch 1 Run 1',
 'Lavaca Wellhausen Comp Disch 2 Run 1',
 'Lavaca West Station Comp Disch 1 Run 1',
 'Lavaca Wombat Comp Disch 1 Run 4',
 'Lavaca Wombat Comp Disch 123 Run 1',
 'Lavaca Wombat Comp Disch 123 Run 2',
 'Lavaca Wombat Comp Disch 123 Run 3',
 'Lavaca Wombat Comp Disch 123 Run 4',
 'Lavaca Wombat Comp Disch 123 Run 5',
 'Lavaca Wombat Comp Disch 2 Run 3',
 'Lavaca Wombat Comp Disch 3 Run 2',
 'Lavaca Wombat Comp Disch 4 Comp 4',
 'Lavaca Wombat Comp Disch 5 Run 1',
 'Lavaca Wombat Comp Disch 6 Run 1',
 'Lavaca Wombat Comp Disch Total Run 1',
 'BRUCITE/KOSMO/PORTER Remote Device',
 'WHITE OAK Remote Device',
 'GEORG EF Remote Device',
 'MAPLE Remote Device',
 'RHEA',
 'HEATWAVE/LEAL',
 'LEAL H',
 'HEATWAVE/LEAL CT GL',
 'HEATWAVE/LEAL CT LPR',
 'HEATWAVE/LEAL/RHEA',
 'HEATWAVE/LEAL/RHEA  Remote Device',
 'RHEA A1H B2H Remote Device',
 'Lavaca Ricatorn B2H Comp Disch',
 'RHEA A1H   - LAVACA',
 'RHEA A1H  - LAVACA',
 'RHEA B2H   - LAVACA',
 'RHEA B2H  - LAVACA',
 'WASHINGTON H   - LAVACA',
 'WASHINGTON H  - LAVACA',
 'PORTER #7H   - LAVACA',
 'PORTER #7H  - LAVACA',
 'BOCK #7H   - LAVACA',
 'BOCK #7H  - LAVACA',
 'EROS',
 'JACKALOPE',
 'EROS A1H Spare',
 'EROS/JACKALOPE',
 'EROS/JACKALOPE Remote Device',
 'TETHYS A 1H   - LAVACA',
 'TETHYS B 2H   - LAVACA',

In [14]:
no_nan_rows = outer_join_02[outer_join_02.notna().all(axis=1)]
no_nan_rows

,item_id,point_name,equipment,parent_equipment_name,equipment_type,well_name,Name,Accounting Number
0,10000,Tubing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H,BIG FIVE A1 H,204600.01
1,10001,Casing Pressure,BIG FIVE A1 H,BIG FIVE Well Pad,Gas Lift,BIG FIVE A1 H,BIG FIVE A1 H,204600.01
2,10002,Tubing Pressure,BIG FIVE B 2H,BIG FIVE Well Pad,Gas Lift,BIG FIVE B 2H,BIG FIVE B 2H,204601.01
3,10003,Casing Pressure,BIG FIVE B 2H,BIG FIVE Well Pad,Gas Lift,BIG FIVE B 2H,BIG FIVE B 2H,204601.01
4,10004,Tubing Pressure,BLOODSTONE C 3H,BLOODSTONE C 3H D 4H Well Pad,Gas Lift,BLOODSTONE C 3H,BLOODSTONE C 3H,204686.01
...,...,...,...,...,...,...,...,...
28341,70278,Last Meter History Collected,HORNED FROG NW 5H Production Meter,HORNED FROG NW 5H,Gas Meter,HORNED FROG NW 5H,HORNED FROG NW 5H,205470.01
28342,70279,Last Meter History Collected,HORNED FROG NW 4H Production Meter,HORNED FROG NW 4H,Gas Meter,HORNED FROG NW 4H,HORNED FROG NW 4H,205180.01
28343,70280,Last Meter History Collected,HORNED FROG NW 3H Production Meter,HORNED FROG NW 3H,Gas Meter,HORNED FROG NW 3H,HORNED FROG NW 3H,205257.01
28344,70281,Last Meter History Collected,HORNED FROG NW 2H Production Meter,HORNED FROG NW 2H,Gas Meter,HORNED FROG NW 2H,HORNED FROG NW 2H,204962.01
28347,70284,Last Meter History Collected,NANCY A 1H Gas Lift Meter,NANCY A 1H,Gas Meter,NANCY A 1H,NANCY A 1H,204435.01